### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by cactusjuan** [sap8899/reportly#1]
Tried to run this but the ips module is missing. Is this a custom module you made?
`Traceback (most recent call last):
  File "/*******/reportly/main.py", line 2, in <module>
    from graph import Graph
  File "/*******/reportly/graph.py", line 12, in <module>
    from ips import IPS
ModuleNotFoundError: No module named 'ips'`

**Comment by sap8899** [comment]
hi :) i updated the code (also added some fun stuff) supposed to work now
